### ISSUE TITLE
2D Art Map

### ISSUE THREAD

**Issue by BecBrock** [GAME-2332/project1#106]
Please create posters for the closed mall with the map of the mall.

Please save as a png.

**Comment by AoTora98** [comment]
Mind tell me which concept maps you want me to improvise?

**Comment by AoTora98** [comment]
![Image](https://user-images.githubusercontent.com/112512808/190514561-39638f71-dbe5-4b06-aa70-3c14c4ff5218.png)

Sorry for the delay.

**Comment by professaurChris** [comment]
Can you add some dirt and grime to it? It's to fit the abandoned aesthetic of the mall.

**Comment by AoTora98** [comment]
![Comparison](https://user-images.githubusercontent.com/112512808/192083710-2a65861f-d270-47a6-a26e-056067df6ef4.png)
![MAP POSTER OLD](https://user-images.githubusercontent.com/112512808/192083718-d754ba81-1e67-4eab-bd87-a45df625c06e.png)

**Comment by BecBrock** [comment]
Approved

**Comment by professaurChris** [comment]
We're good on this.
