### ISSUE TITLE
2D Art Posters

### ISSUE THREAD

**Issue by BecBrock** [GAME-2332/project1#107]
Please make posters for the mall walls. They can be for movies or the shops, anything you would see around the mall. Feel free to be creative!

Save as a png.

[] 3 posters

**Comment by ChrisGoodrum01** [comment]
![Poster(1)](https://user-images.githubusercontent.com/112520495/191403589-54cfa83a-59d0-4253-845f-194ae7f6844d.png)
![Poster(2)](https://user-images.githubusercontent.com/112520495/191403591-f90a978e-c9fb-40b8-906f-d23c8188559a.png)
![Poster(3)](https://user-images.githubusercontent.com/112520495/191403595-3414ea3c-2288-4ef5-8a23-cc97e7d41baa.png)

**Comment by BecBrock** [comment]
Approved

**Comment by professaurChris** [comment]
Please revise these to make them look grittier, possibly add dirt and grime to match the mall's abandoned aesthetics. Refer to previous store front art that you've created @ChrisGoodrum01

**Comment by ChrisGoodrum01** [comment]
![Poster(1)](https://user-images.githubusercontent.com/112520495/191895551-24599d51-8afe-45ca-90c7-6976ebe7aa69.png)
![Poster(2)](https://user-images.githubusercontent.com/112520495/191895553-27861151-3a8f-409c-ba4d-f7c190ba372b.png)
![Poster(3)](https://user-images.githubusercontent.com/112520495/191895556-a3d28d6b-236d-405d-b97d-641366ecc6d7.png)
Is that better?

**Comment by BecBrock** [comment]
They look much better!

**Comment by professaurChris** [comment]
This is good! Approved.
