### ISSUE TITLE
3D Modeling - Quest items

### ISSUE THREAD

**Issue by BecBrock** [GAME-2332/project1#108]
Model the following items. Save as an obj using the naming guidelines.

[] Cryptid Cans
[] Tiara
[] Keys
[] Game Cartridge

[] Power box

**Comment by spiffyspades** [comment]
![Arcade_GameCartridge](https://user-images.githubusercontent.com/112118309/190551916-1532b445-442a-492d-b524-262d051a6140.PNG)
![Foodcourt_Powerbox](https://user-images.githubusercontent.com/112118309/190551917-cf682311-3b8b-41cc-a47d-a72547df6332.PNG)
![JeaniesAccessories_Tiara](https://user-images.githubusercontent.com/112118309/190551920-baa00556-443b-4952-8a05-c2571d85aa37.PNG)
![Quest_Key](https://user-images.githubusercontent.com/112118309/190551922-f37a421c-391b-4597-bf3c-df75fa38f1de.PNG)
![Spicysubject_CriptydCan](https://user-images.githubusercontent.com/112118309/190551924-6081fccd-49f5-49fb-a0ed-c373160446b5.PNG)

**Comment by BecBrock** [comment]
Uploaded and textured.

**Comment by professaurChris** [comment]
Looks okay. Approved.
