### ISSUE TITLE
2D Art Intro/Exit Comic

### ISSUE THREAD

**Issue by BecBrock** [GAME-2332/project1#109]
Please create a comic for the beginning where you fall in the jail hole and ending with the door.
Save as a png.

**Comment by SleepiMitsu** [comment]
[Beginnigand Ending intros.txt](https://github.com/GAME-2332/project1/files/9571579/Beginnigand.Ending.intros.txt)
**To put as the intro and ending of game**

**Comment by BecBrock** [comment]
Great dialogue
