### ISSUE TITLE
Game Pitch

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#11]
Create a game pitch for preproduction. Team must cohesively persuade their producer or publisher about the project they wish to create within eight weeks.

**Comment by professaurChris** [comment]
This is pushed to design progress. Waiting for checklist, posted on Discord already. Will take a look later.

**Comment by BecBrock** [comment]
[Night at the Museum Pitch.pptx](https://github.com/GAME-2332/project1/files/9482085/Night.at.the.Museum.Pitch.pptx)

**Comment by professaurChris** [comment]
Game pitch was approved. Consider refining the power point, and possibly a word document, in the future to include more specific headlines. Some images were provided without literal context.
