### ISSUE TITLE
2D Art - Texture Keypad, Doors

### ISSUE THREAD

**Issue by BecBrock** [GAME-2332/project1#124]
Please create textures for the keypad and doors. I have included the UV maps that need to be filled in. I labeled the different parts of the door and keypad.

![Image](https://user-images.githubusercontent.com/112132801/190513361-f86b64e2-937f-4d15-9d65-597d2af61dc5.png)

![Image](https://user-images.githubusercontent.com/112132801/190513140-1782afee-be24-40a1-9890-036ed7630725.png)
![Image](https://user-images.githubusercontent.com/112132801/190513141-42d5c686-05e7-48f2-a42e-89f3addf51e0.png)
![Image](https://user-images.githubusercontent.com/112132801/190513142-4ff58793-047f-4992-8323-80b4c65973f0.png)
![Image](https://user-images.githubusercontent.com/112132801/190513139-3534ed86-d2f0-4dcf-a51f-fbcbe6e50b8f.png)
![Image](https://user-images.githubusercontent.com/112132801/190513143-cc550add-80cf-4847-bb43-222b696289df.png)

**Comment by AoTora98** [comment]
Sorry took long. The door textures doesn't seem easy. Hope it seem enough.
![Metal 01](https://user-images.githubusercontent.com/112512808/191662160-4e3a4938-a545-4b93-a7a0-0335d00a7b82.png)
![Metal 02](https://user-images.githubusercontent.com/112512808/191662174-30c23e5d-c48b-4c7d-917a-3936f93267e0.png)
![Keypad](https://user-images.githubusercontent.com/112512808/191662183-b5b3e808-d327-4f30-9337-042623695e38.png)
![Redwood](https://user-images.githubusercontent.com/112512808/191662197-2276d72a-625e-4e77-a997-efc4c37e69d6.png)
![Sand Wood](https://user-images.githubusercontent.com/112512808/191662210-93169dd3-c6fa-4cb2-b8f5-73e291247367.png)
![Ectoplasm Door](https://user-images.githubusercontent.com/112512808/191662221-35b9f0dc-5e11-4576-86ce-1d03b627c413.png)

**Comment by AoTora98** [comment]
![Keypad](https://user-images.githubusercontent.com/112512808/191662459-29ca0a9b-d438-446c-8f8d-e656cca8de14.png)

Real Keypad Texture. Ignore the first one above

**Comment by AoTora98** [comment]
Doors
<img width="584" alt="Sandwood Door" src="https://user-images.githubusercontent.com/112512808/191817898-23f6a2a8-e9eb-4d1a-a207-107febf5dda6.png">
<img width="584" alt="Redwood Door" src="https://user-images.githubusercontent.com/112512808/191817903-f105879d-f82c-475e-9d7f-26b78940c810.png">
<img width="584" alt="Ectoplasmic Door" src="https://user-images.githubusercontent.com/112512808/191817905-2fde7cd9-a01c-4ed9-be8a-b179a0b1e8d8.png">

**Comment by AoTora98** [comment]
Keypad
<img width="556" alt="Keypad Complete" src="https://user-images.githubusercontent.com/112512808/191822552-312b4c63-80e6-4804-a417-953e47f65fb3.png">

**Comment by AoTora98** [comment]
<img width="556" alt="Keypad Complete" src="https://user-images.githubusercontent.com/112512808/191822780-7b0167c6-c0de-472a-9a41-ecbd35508c35.png">

**Comment by BecBrock** [comment]
Done

**Comment by professaurChris** [comment]
Looks okay.
