### ISSUE TITLE
2D Art - Texture Clothes Rack, Counter

### ISSUE THREAD

**Issue by BecBrock** [GAME-2332/project1#125]
Please make the textures for the clothes rack and the counter. They can just be a repeating pattern such as wood or metal textures.

![Image](https://user-images.githubusercontent.com/112132801/190510154-6a51fa2c-201c-4527-9246-b86d1fac8d15.png)

**Comment by ChrisGoodrum01** [comment]
![WoodTexture(1)](https://user-images.githubusercontent.com/112520495/191393834-2111ec58-97da-4656-a7c6-3b19825abfbe.png)

**Comment by ChrisGoodrum01** [comment]
![MetalTexture(1)](https://user-images.githubusercontent.com/112520495/191393901-35ce3afd-e3bd-4963-a647-6f003ae852a6.png)
![MetalTexture(2)](https://user-images.githubusercontent.com/112520495/191393904-f5222866-ecb2-42de-9823-a008b002998a.png)

**Comment by ChrisGoodrum01** [comment]
![WoodTexture(1)](https://user-images.githubusercontent.com/112520495/191394094-22a96b85-ae78-4c8d-9620-e5ab6bc9a369.png)
![WoodTexture(2)](https://user-images.githubusercontent.com/112520495/191394095-829b6f07-4066-4b64-82c5-0046c67768ac.png)
![MetalTexture(1)](https://user-images.githubusercontent.com/112520495/191394097-f7c35168-a709-4a45-b168-fe1d4627589b.png)
![MetalTexture(2)](https://user-images.githubusercontent.com/112520495/191394098-cf72b0c7-d351-432d-b01c-a87c766cc7a3.png)

**Comment by BecBrock** [comment]
Approved

**Comment by professaurChris** [comment]
We're good on this.
