### ISSUE TITLE
2D Art - Texture Jail Bars, Chair

### ISSUE THREAD

**Issue by BecBrock** [GAME-2332/project1#126]
Please make the texture for the jail bars and chair. It should just be a repeating pattern such as metal or wood.

![Image](https://user-images.githubusercontent.com/112132801/190514065-40788584-cd6e-4d46-a62d-9af9c8bb0fca.png)

**Comment by Melissa971** [comment]
![Metal_Bump](https://user-images.githubusercontent.com/56281725/191194440-0e8466e7-405b-4ec7-9542-919538add2bc.jpg)
![Metal_Seamless](https://user-images.githubusercontent.com/56281725/191194448-ddd96bc0-ab01-48bf-9e64-d98148d499b5.jpg)
![Metal_Specular](https://user-images.githubusercontent.com/56281725/191194453-6264310b-a246-4aee-9a0d-bae9454bf6b1.jpg)
![Wood_Bump](https://user-images.githubusercontent.com/56281725/191194484-55652f16-f3e9-4b07-a1e8-870e527be9b8.jpg)
![Wood_Seamless](https://user-images.githubusercontent.com/56281725/191194490-d651d62b-6431-4563-9503-306c53791b78.jpg)
![Wood_Specular](https://user-images.githubusercontent.com/56281725/191194492-11b46920-5eaa-4bf3-ac7c-7885f7ed4fb0.jpg)

**Comment by BecBrock** [comment]
Approved

**Comment by professaurChris** [comment]
We're good on this.
