### ISSUE TITLE
2D Art - Shelves, Desk

### ISSUE THREAD

**Issue by BecBrock** [GAME-2332/project1#127]
Please make textures for the shelves and desk. It can be a repeating pattern such as wood or metal.

![Image](https://user-images.githubusercontent.com/112132801/190514632-9a1c77c5-8e62-4915-80f7-a25fd173ce1c.png)

**Comment by bluexsoul** [comment]
![wood1](https://user-images.githubusercontent.com/112124107/190877594-ab2d8a7e-df04-4245-bfff-c7b51a093743.jpg)
![wood2](https://user-images.githubusercontent.com/112124107/190877595-bbc26270-8a29-433f-8447-da4ed143f98c.jpg)
![metal1](https://user-images.githubusercontent.com/112124107/190877596-9ef79d8b-e36a-4ac4-843d-ff3162c28e60.jpg)
![metal2](https://user-images.githubusercontent.com/112124107/190877597-99b7c08e-48f0-41e1-be5d-2dddf01cbd4e.jpg)

**Comment by BecBrock** [comment]
They look great!

**Comment by professaurChris** [comment]
Good to go.
