### ISSUE TITLE
2D Art - Trash Can

### ISSUE THREAD

**Issue by BecBrock** [GAME-2332/project1#128]
Please create the texture for the trash can. The UV map is labeled.

![Image](https://user-images.githubusercontent.com/112132801/190515774-2c4bb552-c5a9-4e13-b1fe-d2bb997d3a65.png)

**Comment by spiffyspades** [comment]
<img width="601" alt="trashcan_texture" src="https://user-images.githubusercontent.com/112118309/191293481-53f08765-39c6-4da7-8ea7-fc226936b78e.png">

**Comment by BecBrock** [comment]
Approved

**Comment by professaurChris** [comment]
Texture does not show up in Unity, incorrect shader.

**Comment by BecBrock** [comment]
Texture shows on all other computers

**Comment by professaurChris** [comment]
Tis be fixed.
