### ISSUE TITLE
Level - Hall

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#133]
Create the hall level in Unity where the entire level is textured.

**Comment by Indazonect** [comment]
![Image](https://user-images.githubusercontent.com/99913991/195396200-d8f52687-fd2c-4f2b-9a97-6b6db9c0fcbc.png)
![Image](https://user-images.githubusercontent.com/99913991/195396199-b3db0682-ead1-42c5-b6e3-cd7d0574458f.png)
![Image](https://user-images.githubusercontent.com/99913991/195396201-e84acb67-8596-419c-a16f-2fbdc7f205f1.png)
![Image](https://user-images.githubusercontent.com/99913991/195396198-2f98ff25-bcf7-4c7a-9e2a-96e79ac09ff1.png)
