### ISSUE TITLE
Concept Art - Characters

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#14]
Create concept characters for: 

1. Shop People?
2. Gamer Guy
3. Accessory Girl
4. Beauty Girl
5. Spicy Subject Guy
6. Segway/Mall Cop
7. Jail Ghost
These models can all be the same basic figure and then adjusted to make the different characters. The only ghost with legs is the Segway Mall Cop.

**Comment by professaurChris** [comment]
Since this is two-task in one, we're focusing on creating these characters as a asset as well. Please follow the checklist listed.

**Comment by SleepiMitsu** [comment]
![Concept_Characters_Gamer1](https://user-images.githubusercontent.com/78447719/188950854-dc2b1c8b-97da-49af-bb9b-42818cc1afbe.png)
Used for Dialogue pop-up

**Comment by SleepiMitsu** [comment]
![Concept_Characters_Gamer2](https://user-images.githubusercontent.com/78447719/188951045-9ceaa8ba-1025-48a9-8509-cfa043609eb7.png)
Used in dialogue pop_up

**Comment by SleepiMitsu** [comment]
![Concept_Characters_Gamer3](https://user-images.githubusercontent.com/78447719/188951178-fac5f602-0ac6-4378-9333-2215f69c1018.png)
Used in dialogue pop-up

**Comment by SleepiMitsu** [comment]
![Concept_Characters_Gamer4](https://user-images.githubusercontent.com/78447719/188951313-0af75283-7f0a-4740-b96e-cb4a48fc50b8.png)
Used at end of quest dialogue pop-up

**Comment by SleepiMitsu** [comment]
![Concept_Characters_Spicy1](https://user-images.githubusercontent.com/78447719/189395667-8b84fb56-6c78-4d53-af61-7188bb9a7e5e.png)
Used in dialogue

**Comment by SleepiMitsu** [comment]
![Concept_Characters_Spicy2](https://user-images.githubusercontent.com/78447719/189395721-6ccad797-d8f3-477a-9c72-68866e622000.png)
Used in dialogue

**Comment by SleepiMitsu** [comment]
![Concept_Characters_Spicy3](https://user-images.githubusercontent.com/78447719/189395790-93dcbb39-7d8a-49ee-84db-01db544ab5a1.png)
Used in dialogue

**Comment by SleepiMitsu** [comment]
[Concept_Characters_GamerAnim.zip](https://github.com/GAME-2332/project1/files/9538454/Concept_Characters_GamerAnim.zip)
Used when dialogue in use

**Comment by SleepiMitsu** [comment]
[ConceptCharacters_BeautyGhostAnim.zip](https://github.com/GAME-2332/project1/files/9541565/ConceptCharacters_BeautyGhostAnim.zip)
Used when in dialogue in use

**Comment by SleepiMitsu** [comment]
![Uploading Concept_Characters_Beauty1.png…]()

**Comment by SleepiMitsu** [comment]
![Concept_Characters_Beauty1](https://user-images.githubusercontent.com/78447719/189505782-dcf9b9a7-1c88-4594-a501-697e85e1cc74.png)

**Comment by SleepiMitsu** [comment]
![Concept_Characters_Beauty2](https://user-images.githubusercontent.com/78447719/189505787-2a93cef3-34e2-4c83-a137-1e4933e95297.png)

**Comment by SleepiMitsu** [comment]
![Concept_Characters_Beauty3](https://user-images.githubusercontent.com/78447719/189505792-852e5b09-3339-4be9-9c51-45c6ed5a435c.png)

**Comment by SleepiMitsu** [comment]
[Uploading Concept_Characters_SSGhostAnim.zip…]()

**Comment by SleepiMitsu** [comment]
[Concept_Characters_SSGhostAnim.zip](https://github.com/GAME-2332/project1/files/9541592/Concept_Characters_SSGhostAnim.zip)

**Comment by SleepiMitsu** [comment]
![Concept_Characters_Child1](https://user-images.githubusercontent.com/78447719/189781314-eca41e0e-c31a-4ace-afdd-6c80bbd3857a.png)

**Comment by SleepiMitsu** [comment]
[Uploading ConceptCharacters_ChildGhostAnim.zip…]()

**Comment by SleepiMitsu** [comment]
[ConceptCharacters_ChildGhostAnim.zip](https://github.com/GAME-2332/project1/files/9552774/ConceptCharacters_ChildGhostAnim.zip)

**Comment by SleepiMitsu** [comment]
[BeautyGhostAnim.zip](https://github.com/GAME-2332/project1/files/9558985/BeautyGhostAnim.zip)
[ChildGhostAnim.zip](https://github.com/GAME-2332/project1/files/9558986/ChildGhostAnim.zip)
[GamerGhost_Anim.zip](https://github.com/GAME-2332/project1/files/9558987/GamerGhost_Anim.zip)
[Ghosts.zip](https://github.com/GAME-2332/project1/files/9558989/Ghosts.zip)
[Mallcop_Ghost.zip](https://github.com/GAME-2332/project1/files/9558990/Mallcop_Ghost.zip)
[SSGhost.zip](https://github.com/GAME-2332/project1/files/9558991/SSGhost.zip)

**Comment by BecBrock** [comment]
Approved and uploaded
