### ISSUE TITLE
Art Asset Fixes

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#144]
These assets need their shaders fixed. Note that there are some duplicates because there are duplicated prefabs. Please clean up your directory to include all generic props in a prefabs folder called 

Directory. Assets/Art/3D/Generic/Prefabs

- [x] SM_Mall_Chair_01
- [x] SM_Mall_Desk_01_1
- [x] SM_Mall_Desk_01_2
- [x] SM_Mall_Shelf_01_1
- [x] SM_Mall_Shelf_01_2
- [x] SM_Mall_Chair_01
- [x] SM_Mall_Desk_01_1
- [x] SM_Mall_Desk_01_2
- [x] SM_Mall_Shelf_01_1
- [x] SM_Mall_Shelf_01_1
- [x] SM_Mall_Chair_01
- [x] SM_Mall_Chair_01
- [x] SM_Mall_Desk_01_1
- [x] SM_Mall_Desk_01_2
- [x] SM_Mall_Shelf_01_1
- [x] SM_Mall_Shelf_01_2
- [x] SM_Mall_Chair_01
- [x] SM_Mall_CothesBar_01
- [x] SM_Mall_Desk_01_1

Directory. Assets/Art/3D/Arcade/Prefabs
Update naming conventions. Example: Prop_Arcade_Cabinet_[Color]_01; Prop_Arcade_Cabinet_Broken_[Color]_01

- [ ] Prop_Arcade_Cabinet_01_1
- [ ] Prop_Arcade_Cabinet_01_2
- [ ] Prop_Arcade_Cabinet_01_3
- [ ] Prop_Arcade_Cabinet_01_4
- [ ] Prop_Arcade_Cabinet_02_1
- [ ] Prop_Arcade_Cabinet_02_2
- [ ] Prop_Arcade_Cabinet_02_3
- [ ] Prop_Arcade_Cabinet_02_4

Directory. Assets/Art/3D/Generic/Prefabs
Update naming conventions. Example: _Prop_Generic_DoubleDoor_[Color]_01_
Separate door and doorframes. 

- [ ] Prop_GenericProp_DoubleDoor01_1
- [ ] Prop_GenericProp_DoubleDoor01_2
- [ ] Prop_GenericProp_DoubleDoor01_3
- [ ] Prop_GenericProp_DoubleDoor02_1
- [ ] Prop_GenericProp_DoubleDoor02_2
- [ ] Prop_GenericProp_DoubleDoor02_3
- [ ] Prop_GenericProp_DoubleDoor02_3
- [ ] Prop_GenericProp_DoubleDoor03_1
- [ ] Prop_GenericProp_DoubleDoor03_2
- [ ] Prop_GenericProp_DoubleDoor03_3

**Comment by BecBrock** [comment]
Fully updated with current assets

**Comment by professaurChris** [comment]
Update double doors and door naming conventions to fit color and door types in the name.

**Comment by BecBrock** [comment]
I don't have any double door prefabs because the doors need to be free moving. My door prefabs currently list glass, black, and wood.

**Comment by professaurChris** [comment]
We're good on this.
