### ISSUE TITLE
3D Modeling - Generic Props 3

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#145]
3D model the assets in the spicy subject store. 

Directory is as follows: 
Assets(rootfolder)/Art/3D/Generic/

../Meshes
../Textures
../Materials
../Prefabs

Your texture files are named T_[SceneName]_[PropName]_01_[TextureFormatType]
Material files are named M_[SceneName]_[PropName]_01
Meshes are named SM_[SceneName]_[PropName]_01
Prefabs are named Prop_[SceneName]_[PropName]_01

Each new type of asset can have new variations, simply +1 for each new one. 

**Checklist**

- [x] Paper Trash
- [x] Paper Trash, Crumpled

**Comment by BecBrock** [comment]
I modeled, textured, and prefabbed paper trash.

**Comment by professaurChris** [comment]
Excellent news.
