### ISSUE TITLE
Concept Art - Environment - Jail, Basement

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#15]
Create concept art for jail and basement. 
You need to make cohesive concept art. Please try to make your art "cute and cartoony," like "Taylor Art." The concept art needs to show the full area you are assigned to make. Please show multiple views of each room so we can see every wall/corner. All furniture, posters, items, etc. should be included.
Taylor and I may revise each piece if it doesn't match the style. This is not meant as an insult or slight to you as an artist. We just need a cohesive style.

Please make everything in photoshop with shelves etc. as their own layers so we can move them if need be.

I'm waiting on the design for the Jail, so if you could just work on what you want the furniture to look like and some arcade art, that would be great.

**Comment by michaelHkitchener** [comment]
![Image](https://user-images.githubusercontent.com/112128020/187825055-038a7de9-3f68-4449-ac7d-3135e341f68e.jpg)
![Image](https://user-images.githubusercontent.com/112128020/187825053-a1d675f6-c5a2-4500-89d5-f71ce41d3e68.jpg)
![Image](https://user-images.githubusercontent.com/112128020/187825054-7dadb371-882d-4bd2-a2a0-e6247346912b.jpg)
![Image](https://user-images.githubusercontent.com/112128020/187825057-321a5290-4255-4b73-a3bb-a1bad6c1dae3.jpg)
![Image](https://user-images.githubusercontent.com/112128020/187825056-df65c94b-3365-4c04-b90f-2f60bf3bdafb.jpg)

**Comment by professaurChris** [comment]
Approved.
