### ISSUE TITLE
2D Art - Logo

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#151]
Sketches are recommended for process. Create logo for the game. High resolution, vector preferred. 

- [x] Team Logo
- [x] Game Title

**Comment by Adicus-Alexander** [comment]
![Ghost_Logo](https://user-images.githubusercontent.com/92056056/192069543-ccb597eb-6aed-4f32-8155-279f75044fd9.svg)

**Comment by Adicus-Alexander** [comment]
![Ghost_Logo1](https://user-images.githubusercontent.com/92056056/192069586-fae9805c-4e80-408c-a567-0097c355868a.png)

**Comment by Adicus-Alexander** [comment]
![Game_Name](https://user-images.githubusercontent.com/92056056/192404053-a5beda40-b770-406a-b6c0-da1ab3bafcfb.svg)

**Comment by BecBrock** [comment]
They look great!

**Comment by professaurChris** [comment]
I like this, but it needs to have something on both dark and light backgrounds.
