### ISSUE TITLE
2D Art - Giant Game Poster

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#152]
36"x72", 600dpi/ppi. Sketches recommended as part of process. 

Create a massive vertical poster for print, advertising your game. 

Include the following: 

- Game art 
- Game Title
- Game Team Logo

**Comment by SleepiMitsu** [comment]
![Game_Poster](https://user-images.githubusercontent.com/78447719/192343777-524c92fd-ec9a-4849-98ca-8038935305de.jpg)

**Comment by BecBrock** [comment]
Looks amazing!

**Comment by SleepiMitsu** [comment]
![Game_Poster](https://user-images.githubusercontent.com/78447719/193099393-9e62913d-0ce2-4bdf-b3ac-ed5292cf1877.jpg)

**Comment by professaurChris** [comment]
Move logo a little further away from the edge, names to be a little larger, reference to existing posters in hallway.
