### ISSUE TITLE
3D Modeling - Extra items

### ISSUE THREAD

**Issue by BecBrock** [GAME-2332/project1#159]
Spicy Subject: (Circular Clothing Rack) Beauty Shop: (Small Desktop Mirror) General: (Trash Objects such as food or cups on the floor) Arcade: (Token Dispense, Couch, Tokens, Candy, Safe) Jail: (Phone, Keyboard)

**Comment by BecBrock** [comment]
Completed clothing rack, mirror, tokens, token dispenser, candy, safe, cup, crumpled cup. The rest of the assets are either already in game or have been deemed not necessary.

**Comment by professaurChris** [comment]
We're good on this.
