### ISSUE TITLE
Concept Art - Environment - Beauty Shop

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#16]
Create concept art for the beauty shop.
You need to make cohesive concept art. Please try to make your art "cute and cartoony," like "Taylor Art." The concept art needs to show the full area you are assigned to make. Please show multiple views of each room so we can see every wall/corner. All furniture, posters, items, etc. should be included.
Taylor and I may revise each piece if it doesn't match the style. This is not meant as an insult or slight to you as an artist. We just need a cohesive style.

Please make everything in photoshop with shelves etc. as their own layers so we can move them if need be.

You have the Makeup Shop which will be a long rectangle with a hole in the wall that will meet up with the Accessory Shop(Becca is making the accessory shop).

**Comment by bluexsoul** [comment]
![Image](https://user-images.githubusercontent.com/112124107/188023624-ffdccd95-bc35-4df3-adfa-635a0fb388ae.jpg)
![Image](https://user-images.githubusercontent.com/112124107/188023625-8d22e214-c8ae-4ef6-a492-b5044f12a2ef.jpg)

**Comment by professaurChris** [comment]
This looks fine. Approved.
