### ISSUE TITLE
Concept Art - Environment - Spicy Subject

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#17]
Create concept art for spicy subject, hot topic knock off. 
You need to make cohesive concept art. Please try to make your art "cute and cartoony," like "Taylor Art." The concept art needs to show the full area you are assigned to make. Please show multiple views of each room so we can see every wall/corner. All furniture, posters, items, etc. should be included.
Taylor and I may revise each piece if it doesn't match the style. This is not meant as an insult or slight to you as an artist. We just need a cohesive style.

Please make everything in photoshop with shelves etc. as their own layers so we can move them if need be.

You're making the art for Spicey Subject, and the store is a medium-sized store, rectangular. Also, could you add in a changing room in the back?

**Comment by spiffyspades** [comment]
![Image](https://user-images.githubusercontent.com/112118309/188282995-f102f3d5-9896-4549-b766-d56a3f7d6a73.jpg)
![Image](https://user-images.githubusercontent.com/112118309/188282993-313ce18b-9297-4d12-907c-709fb6cc8183.jpg)
![Image](https://user-images.githubusercontent.com/112118309/188282994-0cc4cc1f-c21c-4077-b553-0ca5f2c4b021.jpg)

**Comment by professaurChris** [comment]
Approved.
