### ISSUE TITLE
Arcade

### ISSUE THREAD

**Issue by HschwandtHCC** [GAME-2332/project1#178]
Create the level for the arcade including props and art assets as well as quest items and ghosts

**Comment by SBM382** [comment]
![Image](https://user-images.githubusercontent.com/70292179/193386000-b3eb6e0f-0631-4adc-b214-c9bae2093a64.jpg)
![Image](https://user-images.githubusercontent.com/70292179/193385999-a6d79d12-77c9-40b9-83e4-756fae17a9f4.jpg)
![Image](https://user-images.githubusercontent.com/70292179/193386001-87bd4ab8-c89f-428e-aa80-c05b23eb8ddd.jpg)
![Image](https://user-images.githubusercontent.com/70292179/193385998-94134cc0-d7dd-4fe6-a873-0b4871ec46c2.jpg)
![Image](https://user-images.githubusercontent.com/70292179/193386002-54e919d1-ef00-4a67-98cc-9241c7fcc6f4.jpg)
