### ISSUE TITLE
Concept Art - Environment - Food Court

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#18]
Create concept for food court. 
You need to make cohesive concept art. Please try to make your art "cute and cartoony," like "Taylor Art." The concept art needs to show the full area you are assigned to make. Please show multiple views of each room so we can see every wall/corner. All furniture, posters, items, etc. should be included.
Taylor and I may revise each piece if it doesn't match the style. This is not meant as an insult or slight to you as an artist. We just need a cohesive style.

Please make everything in photoshop with shelves etc. as their own layers so we can move them if need be

The food court is going to be a hexagon with some empty shops around the outside. The carousel is going to be in the food court, but Adicus is drawing the carousel. See rough mock up.

![Image](https://user-images.githubusercontent.com/112132801/187583837-0a497b6b-3658-4624-8c06-33389ec5bb12.png)

**Comment by Melissa971** [comment]
![Food Court New](https://user-images.githubusercontent.com/56281725/189043428-86dee9e8-010d-4992-b2c5-2ec9ba522f37.png)
![Food Court View 2](https://user-images.githubusercontent.com/56281725/189043430-db8e0fc0-5720-46a0-9e1b-64a5009a1816.png)

**Comment by professaurChris** [comment]
Approved.
