### ISSUE TITLE
Concept Art - Enviroment - Closed Store(s)

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#19]
Create concept for closed store fronts.
You need to make cohesive concept art. Please try to make your art "cute and cartoony," like "Taylor Art." The concept art needs to show the full area you are assigned to make. Please show multiple views of each room so we can see every wall/corner. All furniture, posters, items, etc. should be included.
Taylor and I may revise each piece if it doesn't match the style. This is not meant as an insult or slight to you as an artist. We just need a cohesive style.

Please make everything in photoshop with shelves etc. as their own layers so we can move them if need be.

You will be working on the empty shop fronts, so you can make the grates that are in front of closed stores and posters

**Comment by ChrisGoodrum01** [comment]
![Store Front(Closed)](https://user-images.githubusercontent.com/112520495/188045872-a4513256-eecf-4b06-b871-7c45e94324b5.jpg)

**Comment by ChrisGoodrum01** [comment]
so what do you think.

**Comment by BecBrock** [comment]
Looks good!

**Comment by professaurChris** [comment]
Approved.
