### ISSUE TITLE
Concept Art - Environment - Accessory Store

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#20]
Create concepts for accessory store. :| 
You need to make cohesive concept art. Please try to make your art "cute and cartoony," like "Taylor Art." The concept art needs to show the full area you are assigned to make. Please show multiple views of each room so we can see every wall/corner. All furniture, posters, items, etc. should be included.
Taylor and I may revise each piece if it doesn't match the style. This is not meant as an insult or slight to you as an artist. We just need a cohesive style.

Please make everything in photoshop with shelves etc. as their own layers so we can move them if need be.

It will be a long thin rectangle with a hole that leads to makeup.

**Comment by BecBrock** [comment]
![Jeannie's Acessories](https://user-images.githubusercontent.com/112132801/187922587-8cdc6e86-b5e9-43fc-a96d-5861a2b263b5.jpg)
![Jeannie's acessories glass doors](https://user-images.githubusercontent.com/112132801/187922652-b66f3d50-fe91-4b35-9d98-77156858566c.jpg)

**Comment by professaurChris** [comment]
Approved.
