### ISSUE TITLE
Concept Art - Environment - Hallway, Play Area

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#21]
Create concepts for hallway and play area. 
You need to make cohesive concept art. Please try to make your art "cute and cartoony," like "Taylor Art." The concept art needs to show the full area you are assigned to make. Please show multiple views of each room so we can see every wall/corner. All furniture, posters, items, etc. should be included.
Taylor and I may revise each piece if it doesn't match the style. This is not meant as an insult or slight to you as an artist. We just need a cohesive style.

Please make everything in photoshop with shelves etc. as their own layers so we can move them if need be.

The play area is going to be relatively small next to the carousel. The halls should be a mixture of good repair and dilapidated. See rough design.

![Image](https://user-images.githubusercontent.com/112132801/187585059-6f0d3ac6-938f-4d3a-9198-68acddaf0cd8.png)

**Comment by Adicus-Alexander** [comment]
![FoodCourtWalkway_PlaySpace](https://user-images.githubusercontent.com/92056056/188520068-5a980727-c1bc-4e2e-a2c9-c6fc3da3c760.png)
![FoodCourtWalkway_2](https://user-images.githubusercontent.com/92056056/188520075-278a1448-adf2-42fc-9399-df012b91cc91.png)
![FoodCourtWalkway_1](https://user-images.githubusercontent.com/92056056/188520081-ae5bb28b-c513-4b52-bbc9-340addd28a4a.png)
![Walkway_empty](https://user-images.githubusercontent.com/92056056/188520095-5488a26d-7ed8-42c3-a428-0440dbf05f4b.png)
![BackHallway_2](https://user-images.githubusercontent.com/92056056/188520103-8c03e084-4307-4a06-89e9-01eb75dd682e.png)
![BackHallway_1](https://user-images.githubusercontent.com/92056056/188520107-66c8ccdc-0236-4f62-b945-2f72975e8d85.png)

**Comment by professaurChris** [comment]
This has been approved by Leads.
