### ISSUE TITLE
Whole Level Outline

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#22]
Create an entire a whole level, outlined from beginning to end defining the rules and the gameplay. Include key legend, chronological series of events, and puzzles if any.

**Comment by HschwandtHCC** [comment]
![Image](https://user-images.githubusercontent.com/70177272/187993240-4bfeb877-4bed-4a86-b184-f6a3d4167355.png)

**Comment by professaurChris** [comment]
Please update the foodcourt with the new update. The revised arcade sketch is scaled more proportionately to the current level but the update may be too small in comparison.

**Comment by HschwandtHCC** [comment]
![Whole Map Level](https://user-images.githubusercontent.com/70177272/189195035-8cd4242b-2adb-489a-b236-271a03b6cbb6.png)

**Comment by professaurChris** [comment]
Approved.
