### ISSUE TITLE
Concept Art - Environment - Arcade

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#23]
Create concepts for arcade. 
You need to make cohesive concept art. Please try to make your art "cute and cartoony," like "Taylor Art." The concept art needs to show the full area you are assigned to make. Please show multiple views of each room so we can see every wall/corner. All furniture, posters, items, etc. should be included.
Taylor and I may revise each piece if it doesn't match the style. This is not meant as an insult or slight to you as an artist. We just need a cohesive style.

Please make everything in photoshop with shelves etc. as their own layers so we can move them if need be.

**Comment by SleepiMitsu** [comment]
![image](https://user-images.githubusercontent.com/78447719/188318319-29632088-7065-4b28-a52c-6314bd4a2f2f.png)

**Comment by SleepiMitsu** [comment]
![ArcadePracticeLayout](https://user-images.githubusercontent.com/78447719/188892257-56ff41e1-365c-42c5-95d3-d36f61c796af.jpg)

**Comment by professaurChris** [comment]
This was approved.
