### ISSUE TITLE
Level Sketch - Arcade

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#30]
Please provide a top down sketch of the inside of a large sized arcade with games, a front desk with snacks, a token cabinet, and prize counter. Use the asset list provided by the art department to get an idea of what will be in the level. Ensure there is a clear key legend so everyone can understand what is within the level, and have it ready to be used for greyboxing. Thanks!

**Comment by SBM382** [comment]
![Arcade layout](https://user-images.githubusercontent.com/70292179/187963659-2ac5cff6-3e77-4290-98e2-43f055702282.jpg)

**Comment by SBM382** [comment]
![Image](https://user-images.githubusercontent.com/70292179/188062149-a1c87b99-fd0e-4201-87fa-b16cab09ee7f.jpg)

**Comment by professaurChris** [comment]
Level is possibly too massive, consolidate with your lead design to see if everything fits in the level. Also, minimize the number of arcade machines. Please also note that you will have roughly 2-3 weeks to work on this level with the artists.

**Comment by SBM382** [comment]
![Image](https://user-images.githubusercontent.com/70292179/188295611-53a43e3a-1cb1-4761-8072-035489dca167.jpg)

The list is updated, based on what the arcade could have.
