### ISSUE TITLE
Level Sketch - Accessory Store

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#31]
Please provide a top down sketch of the inside of a medium sized accessory shop with racks for products and a checkout area. Use the asset list provided by the art department to get an idea of what will be in the level. Ensure there is a clear key legend so everyone can understand what is within the level, and have it ready to be used for greyboxing. Thanks!

**Comment by Daemoncel** [comment]
![Image](https://user-images.githubusercontent.com/112131230/187983194-27495a87-ba5c-4032-ac00-7defd1b339cf.png)
