### ISSUE TITLE
Level Sketch - Spicy Subject

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#32]
Please provide a top down sketch of the inside of a small sized clothing shop with racks for products and a checkout area. Use the asset list provided by the art department to get an idea of what will be in the level. Ensure there is a clear key legend so everyone can understand what is within the level, and have it ready to be used for greyboxing. Thanks!

**Comment by HschwandtHCC** [comment]
![Image](https://user-images.githubusercontent.com/70177272/187977371-e3e3c7be-7ad8-464b-bc6f-f24fbfa0ffc4.png)

Spicy Subject Top Down
