### ISSUE TITLE
Level Sketch - Hallway

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#34]
Please provide a top down sketch of a main hallway with obstacles in place to guide the player down the hall. Add one open store and a few closed off ones. Use the asset list provided by the art department to get an idea of what will be in the level. Ensure there is a clear key legend so everyone can understand what is within the level, and have it ready to be used for greyboxing. Thanks!

**Comment by Indazonect** [comment]
![Image](https://user-images.githubusercontent.com/99913991/187981784-56b691d8-6c46-429b-a246-c38ad70817e4.jpg)

**Comment by professaurChris** [comment]
Please remove the broken pillars as mentioned in class.

**Comment by professaurChris** [comment]
This still needs to be updated.

**Comment by Indazonect** [comment]
![Image](https://user-images.githubusercontent.com/99913991/188932751-50c952ea-8a11-4f5c-a116-1c0e3ca9fc7d.jpg)

**Comment by professaurChris** [comment]
Approved.
