### ISSUE TITLE
Level Sketch - Food Court

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#35]

**Comment by NekotTheBrave** [comment]
Created Food Court Sketch

![Image](https://user-images.githubusercontent.com/67830152/187976714-5c337bef-b8a4-45d1-bc63-2a8c5b292559.png)

**Comment by NekotTheBrave** [comment]
V4

![Image](https://user-images.githubusercontent.com/67830152/188004491-5a4c124d-4734-47e2-9c8e-bd14022d9c43.png)

**Comment by professaurChris** [comment]
New revision is good, approved.
