### ISSUE TITLE
Level Sketch - Jail/Basement

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#36]
Please provide a top down sketch of a basement area with a holding cell, some light storage, and a small flight of stairs leading to a door. Use the asset list provided by the art department to get an idea of what will be in the level. Ensure there is a clear key legend so everyone can understand what is within the level, and have it ready to be used for greyboxing. Thanks!

**Comment by MaximusOctaviusss** [comment]
![Image](https://user-images.githubusercontent.com/112192552/187977380-9516002c-d63a-4b49-8108-a42c9c116985.png)
