### ISSUE TITLE
Greybox - Mall

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#39]
Greybox the entire game for the "Mall" including the stores and jail cell. Make a secondary hallway, secured by a gate that may lead to a secondary part of the mall in case we scope creep the game. Create or utilize an existing character prefab for scale in the scene. Create the functional playthrough of the game. Gameplay should last about 20 minutes, at least.

**Comment by professaurChris** [comment]
Is this ready for testing? This issue is still open.

**Comment by HschwandtHCC** [comment]
Yes it is
________________________________

**Comment by professaurChris** [comment]
Needs an update on the greybox since the merge of the branches.
