### ISSUE TITLE
Concept Art - Environment - Entrance/Atrium

### ISSUE THREAD

**Issue by BecBrock** [GAME-2332/project1#42]
You need to make cohesive concept art. Please try to make your art "cute and cartoony," like "Taylor Art." The concept art needs to show the full area you are assigned to make. Please show multiple views of each room so we can see every wall/corner. All furniture, posters, items, etc. should be included.
Taylor and I may revise each piece if it doesn't match the style. This is not meant as an insult or slight to you as an artist. We just need a cohesive style.

Please model the Entrance/Atrium area

**Comment by AoTora98** [comment]
![Concept_Mall_Entryway_1.png](https://user-images.githubusercontent.com/112512808/188690637-bf250c87-b190-40a2-b832-70cd8572c38f.png)

![Concept_Mall_Entryway_2.png](https://user-images.githubusercontent.com/112512808/188690777-22baa091-bf87-4bf0-8979-d6ee5dc0b154.png)

![Atrium_1.png](https://user-images.githubusercontent.com/112512808/188690932-3fa56dea-7d31-4abc-bad5-0a32686c52c4.png)

**Comment by BecBrock** [comment]
This is approved.
