### ISSUE TITLE
2D Art - Closed Food Court Shops

### ISSUE THREAD

**Issue by BecBrock** [GAME-2332/project1#43]
You need to make cohesive concept art. Please try to make your art "cute and cartoony," "anime style."
Taylor and I may revise each piece if it doesn't match the style. This is not meant as an insult or slight to you as an artist. We just need a cohesive style.

We need some shop fronts in the food court. They're closed and/or broken down. See Food Court drawing for suggested store fronts.

Save your files as PNGs.

**Comment by BecBrock** [comment]
./Meshes
../Textures
../Materials
../Prefabs

Your texture files are named T_[SceneName][PropName]01[TextureFormatType]
Material files are named M[SceneName][PropName]01
Meshes are named SM[SceneName][PropName]01
Prefabs are named Prop[SceneName]_[PropName]_01

**Comment by ChrisGoodrum01** [comment]
![Closed Food Court Storefront(Indian)(Grate1)](https://user-images.githubusercontent.com/112520495/189963969-ddcee649-43a0-4555-9698-7c8b50b0755f.png)

**Comment by ChrisGoodrum01** [comment]
![Closed Food Court Storefront(Indian)(Grate2)](https://user-images.githubusercontent.com/112520495/189964033-9e31b9fc-c32b-40bb-a947-caba9ae8f5d7.png)

**Comment by ChrisGoodrum01** [comment]
![Closed Food Court Storefront(Hotdogs)(Grate1)](https://user-images.githubusercontent.com/112520495/189964078-db85f4a4-1d49-494c-978a-b69b38178c9f.png)

**Comment by ChrisGoodrum01** [comment]
![Closed Food Court Storefront(Hotdogs)(Grate2)](https://user-images.githubusercontent.com/112520495/189964107-7a0ab845-4cd3-414e-9432-ec5af3465350.png)

**Comment by ChrisGoodrum01** [comment]
![Closed Food Court Storefront(Chicken)(Grate1)](https://user-images.githubusercontent.com/112520495/189964157-b30dce28-c7bf-49ae-a082-7212cc1ca47c.png)

**Comment by ChrisGoodrum01** [comment]
![Closed Food Court Storefront(Chicken)(Grate2)](https://user-images.githubusercontent.com/112520495/189964172-e9405274-9e5e-437b-a7f4-04b081e262c9.png)

**Comment by ChrisGoodrum01** [comment]
![Closed Food Court Storefront(Pizza)(Grate1)](https://user-images.githubusercontent.com/112520495/189964194-7f0aecb2-cd7b-4a3a-93fe-11905140c3a6.png)

**Comment by ChrisGoodrum01** [comment]
![Closed Food Court Storefront(Pizza)(Grate2)](https://user-images.githubusercontent.com/112520495/189964208-24fe9bfd-f73b-42d7-b9b4-a1e43f3c1fbf.png)

**Comment by ChrisGoodrum01** [comment]
![Closed Food Court Storefront(Chinese)(Grate1)](https://user-images.githubusercontent.com/112520495/189964249-c88f0bd6-24ff-4eff-a66b-32250919b788.png)

**Comment by ChrisGoodrum01** [comment]
![Closed Food Court Storefront(Chinese)(Grate2)](https://user-images.githubusercontent.com/112520495/189964274-66545ba6-5c9f-44d1-8106-768083890fd2.png)

**Comment by ChrisGoodrum01** [comment]
![Closed Food Court Storefront(Sub)(Grate1)](https://user-images.githubusercontent.com/112520495/189964329-36cc26fc-c49b-43a1-987e-9e9779a69b62.png)

**Comment by ChrisGoodrum01** [comment]
![Closed Food Court Storefront(Sub)(Grate2)](https://user-images.githubusercontent.com/112520495/189964349-836b9da7-aa21-4acb-87a0-ea188676b103.png)

**Comment by ChrisGoodrum01** [comment]
![Closed Food Court Storefront(Salad)(Grate1)](https://user-images.githubusercontent.com/112520495/189964390-8f0c982c-32fe-4094-a905-5ba4db7d7539.png)

**Comment by ChrisGoodrum01** [comment]
![Closed Food Court Storefront(Salad)(Grate2)](https://user-images.githubusercontent.com/112520495/189964413-cfb5118d-d9d1-4afc-a828-38fa25aa91e9.png)

**Comment by professaurChris** [comment]
This looks pretty basic. Cabbage Bowl is spelled incorrectly. There isn't much significant detail between the two images, per store.

**Comment by ChrisGoodrum01** [comment]
![Closed Food Court Storefront(Indian)(1)](https://user-images.githubusercontent.com/112520495/190570495-a5ace23a-81be-4df6-a881-5167e1d4111c.png)

**Comment by ChrisGoodrum01** [comment]
![Closed Food Court Storefront(Indian)(2)](https://user-images.githubusercontent.com/112520495/190570541-39fa5b23-2ca2-42f0-8a8e-71ff0af32164.png)

**Comment by ChrisGoodrum01** [comment]
![Closed Food Court Storefront(Hotdog)(1)](https://user-images.githubusercontent.com/112520495/190570616-22297115-a4e9-4a46-8a92-e2f02ef07522.png)

**Comment by ChrisGoodrum01** [comment]
![Closed Food Court Storefront(Hotdog)(2)](https://user-images.githubusercontent.com/112520495/190570631-ed1dbad6-f87a-4f67-b776-dc09bb5e2605.png)

**Comment by ChrisGoodrum01** [comment]
![Closed Food Court Storefront(Chicken)(1)](https://user-images.githubusercontent.com/112520495/190570680-9d2408cd-6f2e-4a39-9763-a2dc551a1658.png)

**Comment by ChrisGoodrum01** [comment]
![Closed Food Court Storefront(Chicken)(2)](https://user-images.githubusercontent.com/112520495/190570717-c84bdd0a-8eb1-47bb-aebd-0ad0396484d6.png)

**Comment by ChrisGoodrum01** [comment]
![Closed Food Court Storefront(Pizza)(1)](https://user-images.githubusercontent.com/112520495/190570735-b2172b46-54cb-4eba-b175-e13aa3dc1a4f.png)

**Comment by ChrisGoodrum01** [comment]
![Closed Food Court Storefront(Pizza)(2)](https://user-images.githubusercontent.com/112520495/190570771-6c8550e9-a802-48b7-a35d-77a823ad8a58.png)

**Comment by ChrisGoodrum01** [comment]
![Closed Food Court Storefront(Chinese)(1)](https://user-images.githubusercontent.com/112520495/190570820-e638dd9d-11a5-4113-80f2-9f1e84ba380e.png)

**Comment by ChrisGoodrum01** [comment]
![Closed Food Court Storefront(Chinese)(2)](https://user-images.githubusercontent.com/112520495/190570853-94408b90-03c3-4312-9348-356d5e97e9dc.png)

**Comment by ChrisGoodrum01** [comment]
![Closed Food Court Storefront(Subs)(1)](https://user-images.githubusercontent.com/112520495/190570917-ed0f89b3-dd87-4de4-aada-dc7e8099e940.png)

**Comment by ChrisGoodrum01** [comment]
![Closed Food Court Storefront(Subs)(2)](https://user-images.githubusercontent.com/112520495/190570942-610d955a-465a-4e15-b589-fc1d48004522.png)

**Comment by ChrisGoodrum01** [comment]
![Closed Food Court Storefront(Salad)(1)](https://user-images.githubusercontent.com/112520495/190570976-3c5df1e8-c18e-4bf5-b543-11bcdfff293b.png)

**Comment by ChrisGoodrum01** [comment]
![Closed Food Court Storefront(Salad)(2)](https://user-images.githubusercontent.com/112520495/190571040-3a8c0664-24b9-4316-96da-72865b14f7de.png)

**Comment by BecBrock** [comment]
These look better. Thanks for the rework!

**Comment by ChrisGoodrum01** [comment]
Thank You

**Comment by professaurChris** [comment]
Moving this to completed. We are good on this, it's also in the project. Good work.

**Comment by AoTora98** [comment]
I believed it seem better.
