### ISSUE TITLE
Greybox - Foodcourt

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#44]
Greybox the foodcourt, utilizing the scene Hunter has created, "Greybox - Mall."

For the directory, please use the following examples below to create your levels.
Assets(rootfolder)/Levels/SpicySubject/
Assets(rootfolder)/Levels/AccesstoryStore/
Assets(rootfolder)/Levels/Arcade
Assets(rootfolder)/Levels/ClothingStore

Inside these folders, you will save your scene name as [SceneName]. First letter of each word is capitalized. In your folder, there will be another folder with the same name, where you will place your baked light maps. In your hierarchy, create an empty object list:

    Props
    Level
    Greyboxes
    Lighting

Props will contain all of your prefabs, AND ONLY prefabs. Level contains your scene geometry or 3D meshes that make up walls, floor, and other. Lighting includes light sources. Greyboxes is a temporary folder that can be disabled.

**Comment by NekotTheBrave** [comment]
Uploaded greybox to the 'Food Court' branch on github repository.

**Comment by professaurChris** [comment]
Needs an update on the greybox since the merge of the branches.

**Comment by NekotTheBrave** [comment]
![Image](https://user-images.githubusercontent.com/67830152/190246037-1b5789ef-cb08-46cb-9f08-12b7c48464c5.png)
![Image](https://user-images.githubusercontent.com/67830152/190246038-dfb87d77-7250-4898-86b5-eb6a48d94796.png)
![Image](https://user-images.githubusercontent.com/67830152/190246040-8b122f73-1f71-48b7-962b-dd9e8c36017a.png)
![Image](https://user-images.githubusercontent.com/67830152/190246039-023decb7-cfd7-4b03-9509-8e8ba152de6a.png)
