### ISSUE TITLE
Greybox - Arcade

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#45]
Greybox the arcade utilizing the scene Hunter has created, "Greybox - Mall."

For the directory, please use the following examples below to create your levels. 
Assets(rootfolder)/Levels/SpicySubject/
Assets(rootfolder)/Levels/AccesstoryStore/
Assets(rootfolder)/Levels/Arcade
Assets(rootfolder)/Levels/ClothingStore

Inside these folders, you will save your scene name as [SceneName]. First letter of each word is capitalized. In your folder, there will be another folder with the same name, where you will place your baked light maps. In your hierarchy, create an empty object list: 
- Props
- Level
- Greyboxes
- Lighting

Props will contain all of your prefabs, AND ONLY prefabs. Level contains your scene geometry or 3D meshes that make up walls, floor, and other. Lighting includes light sources. Greyboxes is a temporary folder that can be disabled.

**Comment by SBM382** [comment]
![Image](https://user-images.githubusercontent.com/70292179/189276167-a16b350c-485b-4449-a709-33ad896a84ff.jpg)
![Image](https://user-images.githubusercontent.com/70292179/189276166-38c377cf-b2f0-4d5c-945b-ed9219dc7c64.jpg)
![Image](https://user-images.githubusercontent.com/70292179/189276168-db623028-8b0a-4929-bb3a-28febafb349d.jpg)
![Image](https://user-images.githubusercontent.com/70292179/189276169-85a841bd-7591-4bcf-a23b-cc86e8835fb8.jpg)

**Comment by professaurChris** [comment]
Needs an update on the greybox since the merge of the branches.
