### ISSUE TITLE
3D Modeling - Spicy Subject

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#51]
3D model the assets in the spicy subject store. 

Directory is as follows: 
Assets(rootfolder)/Art/3D/SpicySubject/

../Meshes
../Textures
../Materials
../Prefabs

Your texture files are named T_[SceneName]_[PropName]_01_[TextureFormatType]
Material files are named M_[SceneName]_[PropName]_01
Meshes are named SM_[SceneName]_[PropName]_01
Prefabs are named Prop_[SceneName]_[PropName]_01

Each new type of asset can have new variations, simply +1 for each new one. 

**Checklist**

- [x] T-Shirt 1 Dirty
- [x] T-Shirt 2 Dirty 
- [x] Pants 1 Dirty 
- [x] Pants 2 Dirty
- [x] Hanger

**Comment by BecBrock** [comment]
Meshes for two shirts, two pants, and a hanger are modeled and UV mapped. I still need the texture so that I can turn them into prefabs.

**Comment by BecBrock** [comment]
![Image](https://user-images.githubusercontent.com/112132801/189017281-213c701b-5432-4155-98e0-682a0af7f09f.png)

**Comment by BecBrock** [comment]
All items are textured and prefabbed.
