### ISSUE TITLE
3D Modeling - Beauty Shop

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#52]
3D model the assets in the beauty shop.

Directory is as follows:
Assets(rootfolder)/Art/3D/BeautyShop/

../Meshes
../Textures
../Materials
../Prefabs

Your texture files are named T_[SceneName][PropName]01[TextureFormatType]
Material files are named M[SceneName][PropName]01
Meshes are named SM_[SceneName][PropName]01
Prefabs are named Prop_[SceneName]_[PropName]_01

Each new type of asset can have new variations, simply +1 for each new one.

**Checklist**
- [ ] Lipstick
- [ ] Makeup Pallet
- [ ] Makeup Mirror

**Comment by spiffyspades** [comment]
![Image](https://user-images.githubusercontent.com/112118309/190454038-5738cf6d-5f1f-409d-b76e-e5fdf7317c0a.PNG)
![Image](https://user-images.githubusercontent.com/112118309/190454039-87ce9c6d-f75d-4ee9-8038-1e3b7b2b6982.PNG)
![Image](https://user-images.githubusercontent.com/112118309/190454040-6496b385-213a-421d-ba28-063ba403c210.PNG)
