### ISSUE TITLE
3D Modeling - Accessory Store

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#53]
3D model the assets in the accessory store. 

Directory is as follows:
Assets(rootfolder)/Art/3D/AccessoryStore/

../Meshes
../Textures
../Materials
../Prefabs

Your texture files are named T_[SceneName][PropName]01[TextureFormatType]
Material files are named M[SceneName][PropName]01
Meshes are named SM[SceneName][PropName]01
Prefabs are named Prop[SceneName]_[PropName]_01

Each new type of asset can have new variations, simply +1 for each new one.

**Checklist**
- [x] Earring
- [x] Necklace

**Comment by BecBrock** [comment]
[] Round organizer

**Comment by BecBrock** [comment]
Uploaded and prefabbed in Unity.
