### ISSUE TITLE
3D Modeling - Foodcourt

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#54]
3D model the assets in the food court. 

Directory is as follows:
Assets(rootfolder)/Art/3D/FoodCourt/

../Meshes
../Textures
../Materials
../Prefabs

Your texture files are named T_[SceneName][PropName]01[TextureFormatType]
Material files are named M[SceneName][PropName]01
Meshes are named SM[SceneName][PropName]01
Prefabs are named Prop[SceneName]_[PropName]_01

Each new type of asset can have new variations, simply +1 for each new one.

**Comment by BecBrock** [comment]
[] Tables
[] Chairs
[] Tray

**Comment by Adicus-Alexander** [comment]
![Image](https://user-images.githubusercontent.com/92056056/190090442-1260b354-692f-42a1-862f-7c1e74f10bdd.png)

**Comment by BecBrock** [comment]
Textures and materials are added.
