### ISSUE TITLE
3D Modeling - Arcade

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#55]
3D model the assets in the arcade. 

Directory is as follows:
Assets(rootfolder)/Art/3D/Arcade/

../Meshes
../Textures
../Materials
../Prefabs

Your texture files are named T_[SceneName][PropName]01[TextureFormatType]
Material files are named M[SceneName][PropName]01
Meshes are named SM[SceneName][PropName]01
Prefabs are named Prop[SceneName]_[PropName]_01

Each new type of asset can have new variations, simply +1 for each new one.

**Checklist**
- [x] Arcade Cabinet
- [x] Arcade Cabinet Broken

**Comment by BecBrock** [comment]
![Image](https://user-images.githubusercontent.com/112132801/189157267-0c404293-6612-4dbf-9116-82e7065c18dd.png)

**Comment by professaurChris** [comment]
Please fix the naming convention on the "game box1" and "game box2." Follow the example provided in the description, i.e. SM_Arcade_Cabinet_01, SM_Arcade_Cabinet_02.

**Comment by BecBrock** [comment]
Uploaded and ready.
