### ISSUE TITLE
3D Modeling - NPC Ghost

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#56]
3D model the NPC ghost.

Directory is as follows:
Assets(rootfolder)/Art/3D/NPCGhosts/

../Meshes
../Textures
../Materials
../Prefabs

Your texture files are named T_[SceneName][PropName]01[TextureFormatType]
Material files are named M[SceneName][PropName]01
Meshes are named SM[SceneName][PropName]01
Prefabs are named Prop[SceneName]_[PropName]_01

Each new type of asset can have new variations, simply +1 for each new one.

**Comment by SleepiMitsu** [comment]
[3DModel_MallCop.zip](https://github.com/GAME-2332/project1/files/9537094/3DModel_MallCop.zip)

**Comment by SleepiMitsu** [comment]
[3dModel_Npc_Ghosts.zip](https://github.com/GAME-2332/project1/files/9537098/3dModel_Npc_Ghosts.zip)

**Comment by professaurChris** [comment]
Need to add this to Unity for testing.

**Comment by SleepiMitsu** [comment]
[Ghosts.zip](https://github.com/GAME-2332/project1/files/9567677/Ghosts.zip)

**Comment by BecBrock** [comment]
Uploaded

**Comment by professaurChris** [comment]
We're good.
