### ISSUE TITLE
3D Modeling - Segway Ghost

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#57]
3D model the Segway Ghost.

Directory is as follows:
Assets(rootfolder)/Art/3D/SegwayGhost/

../Meshes
../Textures
../Materials
../Prefabs

Your texture files are named T_[SceneName][PropName]01[TextureFormatType]
Material files are named M[SceneName][PropName]01
Meshes are named SM[SceneName][PropName]01
Prefabs are named Prop[SceneName]_[PropName]_01

Each new type of asset can have new variations, simply +1 for each new one.

**Comment by SleepiMitsu** [comment]
[3DModel_MallCop.zip](https://github.com/GAME-2332/project1/files/9536976/3DModel_MallCop.zip)

**Comment by professaurChris** [comment]
Need this to be implemented in Unity to be tested.

**Comment by SleepiMitsu** [comment]
[Mallcop_Ghost.zip](https://github.com/GAME-2332/project1/files/9567746/Mallcop_Ghost.zip)

**Comment by BecBrock** [comment]
Uploaded, ready for testing

**Comment by professaurChris** [comment]
We're good.
