### ISSUE TITLE
Art Assets List

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#59]
Refine art assets list. Separate the list by environment types and core assets to be completed. Please provide responses in comments, do not revise this section. Leads must consolidate on a list of required assets for the gameplay. 

### 3D Assets - Props
**3D - General**

- [x] Trash Can
- [x] Grass
- [x] Floor Tiles
- [x] Poster
- [x] Paper Trash
- [x] Paper Trash, Crumpled 
- [x] Vending Machine
- [x] Store Shelves
- [x] Cash Register
- [x] Wall Clothing Rack
- [x] Front Desk
- [x] Wooden Bench
- [x] Office Chair
- [x] Stool
- [x] Light Round
- [x] Light Square
- [x] Glass Door
- [x] Wooden Door
- [x] Framed Advertisement
- [x] Number Key Pad

**3D - Arcade**

- [x] Arcade Cabinet
- [x] Arcade Cabinet Broken

**3D - Spicy Subject**

- [x] T-Shirt 1 Dirty
- [x] T-Shirt 2 Dirty
- [x] Pants 1 Dirty
- [x] Pants 2 Dirty
- [x] Hanger

**3D - Jail**

- [x] Prison Bar
- [x] Prison Bench

**3D - Accessory Store**

- [x] Earring
- [x] Necklace

**3D - Beauty Store**

- [x] Lipstick
- [x] Makeup Pallet 
- [x] Makeup Mirror

**3D - Carousel**

- [x] Horse 1
- [x] Horse 2
- [x] Platform
- [x] Ceiling 

### 2D Assets
**Textures**
These textures are meant to be utilized in 3D environments; floor, walls, and ceiling. Textures must be seamless. This will primarily be utilized by designers. 

- [x] Carpet 
- [x] Marble 
- [x] Plaster
- [x] Concrete
- [x] Dirt
- [x] Grass

**Decals**
These decals are to be completed by 2D artists, dealing with 3D assets that can have palette swaps. This will primarily be utilized by designers. 
- [x] Movie Ad 1
- [x] Movie Ad 2
- [x] Movie Ad 3
- [ ] Make Up Ad 1
- [ ] Make Up Ad 2
- [ ] Make Up Ad 3
- [x] Video Game Ad 1
- [x] Video Game Ad 2
- [x] Video Game Ad 3
- [x] Food Ad 1
- [x] Food Ad 2
- [x] Food Ad 3
- [ ] Mall Cop Ad 1
- [ ] Mall Cop Ad 2
- [ ] Mall Cop Ad 3
- [x] Paper Trash 1
- [x] Paper Trash 2
- [x] Paper Trash 3

**User Interface**

- [x] Heads Up Display
- [x] Menu System
- [x] Ghost Portraits 
- [x] Dialogue Boxes

**Comment by aeonic-dev** [comment]
Dialogue box design and art for ghosts in the dialogue (profile I guess) is another we had discussed; are we going to do those?

**Comment by BecBrock** [comment]
Art is currently working on the ghost images for the dialogue boxes. They're a 3/4 view of the full ghost.

**Comment by professaurChris** [comment]
Added ghost boxes and ghost portraits on the checklist. This will be implemented into tasks after.

**Comment by BecBrock** [comment]
2D Art Assets
[] 3 t-shirts
[] 3 Arcade boxes
[] 3 Posters to match the arcade boxes
[] Air hockey table
[] Drop ceiling(ceiling tiles)
[] Painted wall
[] Wall with stripe
[] Wall with water damage
[] Wall with chipped paint
[] Skylight ceiling

**Comment by professaurChris** [comment]
Closing this issue, because it is no longer relevant.
