### ISSUE TITLE
Movement system overhaul

### ISSUE THREAD

**Issue by aeonic-dev** [GAME-2332/project1#6]
- [x] Clean up movement scripts, switch sprint/crouch status to an enum
- [x] Full rewrite with CharacterController
- [x] Remove speed cap, find a better way to dampen velocity

**Comment by aeonic-dev** [comment]
Optional extras for later:
- [ ] Stamina - limited sprinting; regenerates over time. Either a UI indicator or screen coloration or something
- [ ] Footstep/breath sounds matching sprint/crouch/normal walk mode, possibly dependant on a tag or something to determine the material the player is walking on

**Comment by professaurChris** [comment]
Looks good!
