### ISSUE TITLE
2D Art UI

### ISSUE THREAD

**Issue by BecBrock** [GAME-2332/project1#61]
Draw a refined (ready to be put in the game) backpack for the inventory.
Draw the battery life and UI components (selection hand, interact button, menu, etc.).

UI_HUD_[Type].png or something similar. 

Directory is as follows: 
Assets(rootfolder)/Art/UserInterface/HUD

Listed below are your image files, each image file must contain an separated asset within the image (not-overlapping). 
UI_InventoryScreen.png

- [x] Backpack Background
- [x] Squarebox

UI_HUD.png
- [x] Battery 

UI_Menu.png
- [x] Start
- [x] Options
- [x] Credits
- [x] Quit

UI_Gameplay.png
- [x] Speech Bubble/Box
- [x] Interact Button

**Comment by BecBrock** [comment]
This is the original mockup. We need a large backpack, a battery (full, half full, empty), an interact icon, a talk icon, and the menu. We don't currently need the hand or the full overlay. I will let you know if that changes.

![Image](https://user-images.githubusercontent.com/112132801/188547356-5c060a35-fd91-4907-be21-4c47b5e665c3.jpg)

**Comment by Adicus-Alexander** [comment]
![Image](https://user-images.githubusercontent.com/92056056/188991340-262a6bfd-2fcb-4ac4-b883-a703d184c56b.png)



![Image](https://user-images.githubusercontent.com/92056056/188991370-035675d8-d3b0-4710-bbf6-553964cf9cac.png)
![Image](https://user-images.githubusercontent.com/92056056/188991371-464df2de-bd89-43a1-893a-36881d323edf.png)
![Image](https://user-images.githubusercontent.com/92056056/188991373-91989fd0-a80e-4847-bb07-02a1a02520f8.png)
![Image](https://user-images.githubusercontent.com/92056056/188991375-bdc922ed-9931-4214-8f67-5e7354e7c978.png)
![Image](https://user-images.githubusercontent.com/92056056/188991372-18aa7cac-88ad-43c7-a149-a9d306c90620.png)
![Image](https://user-images.githubusercontent.com/92056056/188991374-16b13f03-6046-4300-9215-300920db08df.png)



![Image](https://user-images.githubusercontent.com/92056056/188991795-2e4d872a-16ec-43ed-809c-33577fee49ac.gif)



![Image](https://user-images.githubusercontent.com/92056056/188991412-8e1729c2-8470-45e4-b530-b7d1eb28d8eb.png)
![Image](https://user-images.githubusercontent.com/92056056/188991410-b4ddb5df-f1bc-46f1-9b20-625412341259.png)
![Image](https://user-images.githubusercontent.com/92056056/188991411-ade81fbc-ee3e-4b9e-a284-9eec7329610d.png)
![Image](https://user-images.githubusercontent.com/92056056/188991414-102187b1-9af9-4442-8ec8-97eb7be6199c.png)
![Image](https://user-images.githubusercontent.com/92056056/188991413-dbc05382-c10e-4e7f-a943-e05e6ea155e7.png)



![Image](https://user-images.githubusercontent.com/92056056/188991815-7693e41a-6f3e-4f42-8776-5957d19dc8e3.gif)

**Comment by Adicus-Alexander** [comment]
Talk Icon is run at 4 fps
Interact Icon is run at 8 fps

**Comment by Adicus-Alexander** [comment]
![UI_Gameplay_DialogueBox_BeautyShop_Ghost](https://user-images.githubusercontent.com/92056056/189425186-21ed9538-b1e8-4ed5-a7c8-4e5fb6dd8024.png)
![UI_Gameplay_DialogueBox_SpicySubject_Ghost](https://user-images.githubusercontent.com/92056056/189425188-244e1d7b-b4e4-4913-a9cc-dd3941854f2a.png)
![UI_Gameplay_DialogueBox_AccessoryShopGhost](https://user-images.githubusercontent.com/92056056/189425189-d6d8743b-580b-4fd5-aae2-1be22bcf42cf.png)
![UI_Gameplay_DialogueBox_Arcade_Ghost](https://user-images.githubusercontent.com/92056056/189425190-b886f798-719c-45a7-b1af-8aae8aeb7152.png)

**Comment by Adicus-Alexander** [comment]
![UI_Gameplay_DialogueBox_Jail_Ghost](https://user-images.githubusercontent.com/92056056/189427937-abe3efec-6171-4cac-89eb-14f2f607c0a2.png)

**Comment by Adicus-Alexander** [comment]
![UI_Gameplay_DialogueBox_MallCop_Ghost](https://user-images.githubusercontent.com/92056056/189430532-53454239-3cc3-4fba-b2f4-cf927d365235.png)

**Comment by Adicus-Alexander** [comment]
![UI_HUD_Battery_75%](https://user-images.githubusercontent.com/92056056/189434493-f8e375d7-6f5f-454d-b053-a61f4ce296a5.png)
![UI_HUD_Battery_Full](https://user-images.githubusercontent.com/92056056/189434494-cdcf5593-8195-4158-80e9-370964362aaf.png)
![UI_HUD_Battery_25%](https://user-images.githubusercontent.com/92056056/189434498-e3167014-8b8d-41bf-92ed-1cb68c29f0e9.png)
![UI_HUD_Battery_50%](https://user-images.githubusercontent.com/92056056/189434500-9d5af6c5-7aac-4dda-b777-bd89f4f99507.png)

**Comment by Adicus-Alexander** [comment]
![UI_Menu_Quit_Yellow](https://user-images.githubusercontent.com/92056056/189475607-229658e0-4c3c-48ae-8de7-73b532133d61.png)
![UI_Menu_Start_Green](https://user-images.githubusercontent.com/92056056/189475609-5e32fb19-46bc-41e8-863d-2488bba8de47.png)
![UI_Menu_Start_Yellow](https://user-images.githubusercontent.com/92056056/189475610-ed641dfb-85b2-4fc1-83e9-059f52619bb1.png)
![UI_Menu_Credits_Green](https://user-images.githubusercontent.com/92056056/189475611-26457c2b-65d8-4cd3-8103-19bd7a3b37c0.png)
![UI_Menu_Credits_Yellow](https://user-images.githubusercontent.com/92056056/189475612-76a4e55a-9596-4be4-b22f-db50cb54454a.png)
![UI_Menu_Options_Green](https://user-images.githubusercontent.com/92056056/189475613-bdc08bb4-26be-42bb-85d4-d76fea44c7f0.png)
![UI_Menu_Options_Yellow](https://user-images.githubusercontent.com/92056056/189475614-b120838c-e42b-4cfa-b670-728eb740fb07.png)
![UI_Menu_Quit_Green](https://user-images.githubusercontent.com/92056056/189475616-a515a35a-e9b8-40dc-8c90-6f33784d59db.png)

**Comment by BecBrock** [comment]
Approved. All of it is perfect!

**Comment by professaurChris** [comment]
Excellent.
