### ISSUE TITLE
User Interface - Loading Screen

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#63]
Create loading screen. Formatting for images should be, 

UI_LoadingScreen_[Type].png or something similar. 

Directory is as follows: 
Assets(rootfolder)/Art/UserInterface/LoadingScreen

**Comment by SleepiMitsu** [comment]
![UI_BG_Art](https://user-images.githubusercontent.com/78447719/190275699-1816beff-0b19-4d39-90f7-013250334a46.jpg)

**Comment by SleepiMitsu** [comment]
![LOADINGPROTO](https://user-images.githubusercontent.com/78447719/190288263-ba299139-363f-484f-9753-e5e24b045f36.gif)

**Comment by SleepiMitsu** [comment]
[UI Background Title.zip](https://github.com/GAME-2332/project1/files/9571421/UI.Background.Title.zip)

**Comment by SleepiMitsu** [comment]
![UI_LoadingScreen](https://user-images.githubusercontent.com/78447719/190308023-39dfd52d-4a06-4012-bb76-ffdcc932f049.png)

**Comment by BecBrock** [comment]
Looks amazing, approved.

**Comment by professaurChris** [comment]
@awetos Will have to slice it in Unity to separate the assets.
