### ISSUE TITLE
3D Modeling - Generic Props

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#65]
3D model the assets. 

Directory is as follows: 
Assets(rootfolder)/Art/3D/Generic/

../Meshes
../Textures
../Materials
../Prefabs

Your texture files are named T_[SceneName]_[PropName]_01_[TextureFormatType]
Material files are named M_[SceneName]_[PropName]_01
Meshes are named SM_[SceneName]_[PropName]_01
Prefabs are named Prop_[SceneName]_[PropName]_01

Each new type of asset can have new variations, simply +1 for each new one. 

**Checklist**
- [x] Trashcan
- [x] Store Shelves
- [x] Cash Register
- [x] Wall Clothing Rack
- [x] Front Desk
- [x] Wooden Bench
- [x] Office Chair
- [x] Stool

**Comment by BecBrock** [comment]
![Image](https://user-images.githubusercontent.com/112132801/189804107-404ce48b-a29f-4887-86d0-c72c400af10a.png)
![Image](https://user-images.githubusercontent.com/112132801/189804106-e3629820-2e7b-4489-b36e-caa6e1116f60.png)
![Image](https://user-images.githubusercontent.com/112132801/189804105-f2ce89ca-0671-426b-9f2d-6df869f8bcc6.png)

**Comment by BecBrock** [comment]
Uploaded and prefabbed.
