### ISSUE TITLE
3D Modeling - Generic Props 2

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#66]
3D model the assets. 

Directory is as follows: 
Assets(rootfolder)/Art/3D/Generic/

../Meshes
../Textures
../Materials
../Prefabs

Your texture files are named T_[SceneName]_[PropName]_01_[TextureFormatType]
Material files are named M_[SceneName]_[PropName]_01
Meshes are named SM_[SceneName]_[PropName]_01
Prefabs are named Prop_[SceneName]_[PropName]_01

Each new type of asset can have new variations, simply +1 for each new one. 

**Checklist**
- [x] Glass Door
- [x] Wooden Door
- [x] Framed Advertisement
- [x] Number Key Pad
- [x] Light Round
- [x] Light Square
- [x] Poster
- [x] Vending Machine

**Comment by Adicus-Alexander** [comment]
![Image](https://user-images.githubusercontent.com/92056056/190090325-0c0c215b-3381-4097-bd75-1722e6514cd8.png)

**Comment by BecBrock** [comment]
Uploaded and prefabbed.
