### ISSUE TITLE
3D Modeling - Prison

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#67]
3D model the assets in the prison.

Directory is as follows: 
Assets(rootfolder)/Art/3D/Prison/

../Meshes
../Textures
../Materials
../Prefabs

Your texture files are named T_[SceneName]_[PropName]_01_[TextureFormatType]
Material files are named M_[SceneName]_[PropName]_01
Meshes are named SM_[SceneName]_[PropName]_01
Prefabs are named Prop_[SceneName]_[PropName]_01

Each new type of asset can have new variations, simply +1 for each new one. 

**Checklist**

- [x] Prison Bar
- [x] Prison Bench

**Comment by BecBrock** [comment]
Assets are modeled but not textured.

**Comment by BecBrock** [comment]
![Image](https://user-images.githubusercontent.com/112132801/189805193-5310e7cc-5e3c-464d-be23-b94b6429643b.png)

**Comment by BecBrock** [comment]
![Image](https://user-images.githubusercontent.com/112132801/189983952-1b968d64-3d3c-48e8-bbec-b6052188cc9d.png)

**Comment by BecBrock** [comment]
Jail bars, bench, and door are textured and converted to prefabs.

**Comment by professaurChris** [comment]
Fix URP issues with shaders, update on Github repo. URP Shaders Complex or Simple.

**Comment by BecBrock** [comment]
It should be fixed. I had Hunter check it on his account to be sure.
