### ISSUE TITLE
3D Modeling - Playground

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#69]
3D model the assets in the playground. 

Directory is as follows: 
Assets(rootfolder)/Art/3D/Playground/

../Meshes
../Textures
../Materials
../Prefabs

Your texture files are named T_[SceneName]_[PropName]_01_[TextureFormatType]
Material files are named M_[SceneName]_[PropName]_01
Meshes are named SM_[SceneName]_[PropName]_01
Prefabs are named Prop_[SceneName]_[PropName]_01

Each new type of asset can have new variations, simply +1 for each new one. 

**Checklist**

- [x] Slides
- [x] Swingset

**Comment by BecBrock** [comment]
I modeled, textured, and prefabbed a slide, swing set, monkey bars, and seesaw.

**Comment by professaurChris** [comment]
Good, on this.
