### ISSUE TITLE
3D Modeling - Carousel

### ISSUE THREAD

**Issue by professaurChris** [GAME-2332/project1#70]
3D model the assets for the carousel.

Directory is as follows: 
Assets(rootfolder)/Art/3D/Carousel/

../Meshes
../Textures
../Materials
../Prefabs

Your texture files are named T_[SceneName]_[PropName]_01_[TextureFormatType]
Material files are named M_[SceneName]_[PropName]_01
Meshes are named SM_[SceneName]_[PropName]_01
Prefabs are named Prop_[SceneName]_[PropName]_01

Each new type of asset can have new variations, simply +1 for each new one. 

**Checklist**
- [x] Horse 1
- [x] Horse 2
- [x] Platform
- [x] Ceiling

**Comment by BecBrock** [comment]
![Image](https://user-images.githubusercontent.com/112132801/189520916-23d246ae-9942-4e4b-946f-7e18c1d75d7e.png)

**Comment by BecBrock** [comment]
![Image](https://user-images.githubusercontent.com/112132801/189558865-821d4733-3846-4fb0-bd42-0d1b0336755e.png)

**Comment by BecBrock** [comment]
The carousel is modeled.

**Comment by BecBrock** [comment]
![Image](https://user-images.githubusercontent.com/112132801/189601697-0ca9a863-6f3e-4693-9bbc-96a264bd7a9e.png)

**Comment by BecBrock** [comment]
All pieces are uploaded and turned into prefabs.

**Comment by professaurChris** [comment]
Add collision boxes to all of the meshes.

**Comment by professaurChris** [comment]
Moving this to completed, cleaning up tasks on Github Projects. Task #171 has is new task.
