### ISSUE TITLE
2D Art Beauty and Accessory Shop Items

### ISSUE THREAD

**Issue by BecBrock** [GAME-2332/project1#74]
Make 2D art of these items. They will be put on rectangular items. They are going to be UV Maps.

Create texture names in file format
T_[StoreName][TeatureName][Description]_[#]_Base.png

Example:
T_Generic_Carpet_Blue_01_Base.png
T_Generic_Carpet_Red_01_Base.png
T_Arcade_Carpet_Galaxy_01_Base.png
T_Arcade_Carpet_DarkGreen_01_Base.png
T_Generic_Marble_White_01_Base.png
T_Generic_Marble_White_02_Base.png
T_Generic_Marble_White_03_Base.png

 [] Earring
 [] Necklace
 [] Lipstick
 [] Makeup Pallet
 [] Makeup Mirror

**Comment by bluexsoul** [comment]
![Siren'sAllure_2d_BeautyStore_Assecory_#1_ png](https://user-images.githubusercontent.com/112124107/190270229-a7b3fd8c-07ec-4541-b3ce-16addfb4900f.png)

**Comment by BecBrock** [comment]
Approved.
