### ISSUE TITLE
2D Art Wall and Ceiling Textures

### ISSUE THREAD

**Issue by BecBrock** [GAME-2332/project1#75]
Create ceiling and wall textures saved in png format (see examples below). Textures should be able to be used as UV maps.

[] Drop ceiling(ceiling tiles)
[] Painted wall
[] Wall with stripe
[] Wall with water damage
[] Wall with chipped paint
[] Skylight ceiling

Create texture names in file format
T_[StoreName][TeatureName][Description]_[#]_Base.png

Example:
T_Generic_Carpet_Blue_01_Base.png
T_Generic_Carpet_Red_01_Base.png
T_Arcade_Carpet_Galaxy_01_Base.png
T_Arcade_Carpet_DarkGreen_01_Base.png
T_Generic_Marble_White_01_Base.png
T_Generic_Marble_White_02_Base.png
T_Generic_Marble_White_03_Base.png

**Comment by AoTora98** [comment]
Sorry delay. Let me know if I missed anything.

**Comment by AoTora98** [comment]
![T_Generic_Painted_Wall_Blue_Base.png](https://user-images.githubusercontent.com/112512808/189465277-c04ed762-6a08-4fd4-9e9f-17bf61db9bc6.png)![T_Generic_Painted_Wall_Green_Base (1).png](https://user-images.githubusercontent.com/112512808/189465283-f9b2cac0-f90b-4433-941f-cfdbcddbf4a4.png)![T_Generic_Painted_Wall_Orange_Base.png](https://user-images.githubusercontent.com/112512808/189465285-e0c71bdb-15dd-467d-a8fd-0d92cc77c4cf.png)![T_Generic_Painted_Wall_Red_Base.png](https://user-images.githubusercontent.com/112512808/189465289-7c104314-6597-464b-a293-b46b53fe1cc9.png)![T_Generic_Painted_Wall_Violet_Base.png](https://user-images.githubusercontent.com/112512808/189465292-c43c3f77-7ece-466c-9913-dbe225ac04af.png)![T_Generic_Painted_Wall_Yellow_Base.png](https://user-images.githubusercontent.com/112512808/189465296-41d3996e-2295-47da-ae14-4388f479bed3.png)![T_Generic_Striped_Wall_Brazil_Base.png](https://user-images.githubusercontent.com/112512808/189465298-8bc203da-cb23-413c-9f6f-87e9743f8a02.png)![T_Generic_Striped_Wall_Circus_Base.png](https://user-images.githubusercontent.com/112512808/189465302-9906b25a-a48b-4d29-a9b8-72ad797ef71e.png)![T_Generic_Striped_Wall_Circus_Base.png]![T_Generic_Striped_Wall_Gothic_Base.png](https://user-images.githubusercontent.com/112512808/189465316-04b5f0fb-76d2-4573-aeea-c49421e2ac03.png)![T_Generic_Striped_Wall_Iridescent_02_Base.png](https://user-images.githubusercontent.com/112512808/189465318-bfbd2aad-aca2-4831-b6ab-76e749eae31c.png)![T_Generic_Striped_Wall_Iridescent_03_Base.png](https://user-images.githubusercontent.com/112512808/189465323-de1e7b48-815c-4d9c-8163-f0659743bff5.png)![T_Generic_Striped_Wall_Iridescent_Base.png](https://user-images.githubusercontent.com/112512808/189465329-8895e6ae-34b1-4be9-adee-f033a52959d9.png)![T_Generic_Striped_Wall_Magenta_Base.png](https://user-images.githubusercontent.com/112512808/189465332-fb46aee5-f760-4ecb-bc72-abebe2ae20f8.png)![T_Generic_Striped_Wall_Mardi_Gras_Base.png](https://user-images.githubusercontent.com/112512808/189465334-3151a151-056d-4868-af5e-0070cf2ffea7.png)![T_Generic_Striped_Wall_Pinky_Base (1).png](https://user-images.githubusercontent.com/112512808/189465341-2a33f2fe-9cac-46ab-8f76-bf8a99fef96e.png)![T_Generic_Striped_Wall_Riddler_Base.png](https://user-images.githubusercontent.com/112512808/189465344-df1ab797-1b73-4a2a-8ff4-b4592c39e26f.png)![T_Generic_Water_Damage_Wall_Base.png](https://user-images.githubusercontent.com/112512808/189465346-58ce7e17-df1f-44f3-84e4-d92eeebe7d16.png)![T_Generic_Ceiling_Tile_Base.png](https://user-images.githubusercontent.com/112512808/189465349-464244d5-b2f1-46c6-baa2-0e337383b81b.png)![T_Generic_Skylight_Ceiling_Base.png](https://user-images.githubusercontent.com/112512808/189465352-53008958-b3e3-4a22-b520-c4ac90051343.png)

**Comment by BecBrock** [comment]
We could use some more toned down colors. Most walls in the mall are more muted colors. See the photos attached for reference.

![Image](https://user-images.githubusercontent.com/112132801/189470344-ccca2c53-e2be-4d73-878c-5c116e66620b.jpg)
![Image](https://user-images.githubusercontent.com/112132801/189470345-040616f9-5a65-443a-ace8-3141a0bd126c.jpg)
![Image](https://user-images.githubusercontent.com/112132801/189470349-2444c0e2-8d9e-4053-a8a2-1b86ba156576.jpg)
![Image](https://user-images.githubusercontent.com/112132801/189470346-467d5cd7-1ed7-4b27-a574-ab4625e2e0ab.jpg)
![Image](https://user-images.githubusercontent.com/112132801/189470347-a6e2ab9e-1ffe-4275-a676-e396a3a23754.jpg)
![Image](https://user-images.githubusercontent.com/112132801/189470348-8492b246-f8d4-4959-a4f7-f35f5b1ec55b.jpg)

**Comment by AoTora98** [comment]
Oh ok, like simple paints. I'll start working on it now.

**Comment by AoTora98** [comment]
![T_Generic_Wall_Color_9_Base.png](https://user-images.githubusercontent.com/112512808/189477915-06f56446-9591-4f46-bd51-e8af1ba62d2a.png)![T_Generic_Wall_Color_8_Base.png](https://user-images.githubusercontent.com/112512808/189477918-2ad88096-e3bb-4a52-bfba-332614a92dce.png)![T_Generic_Wall_Color_7_Base.png](https://user-images.githubusercontent.com/112512808/189477926-c25106e0-dcf4-4da3-8331-4cf9107541f8.png)![T_Generic_Wall_Color_6_Base.png](https://user-images.githubusercontent.com/112512808/189477931-4c9d54ae-24d8-4b4f-8235-45af8ad42744.png)[]()![T_Generic_Wall_Color_5_Base.png](https://user-images.githubusercontent.com/112512808/189477945-28305359-863b-4670-b2da-7ce163f4ec68.png)![T_Generic_Wall_Color_4_Base.png](https://user-images.githubusercontent.com/112512808/189477951-75c7fef1-003a-46d1-9da3-92fd3e74ed46.png)![T_Generic_Wall_Color_3_Base.png](https://user-images.githubusercontent.com/112512808/189477962-4b2ed732-4f91-46ea-b1c2-c3eae4a8ae6b.png)![T_Generic_Wall_Color_2_Base.png](https://user-images.githubusercontent.com/112512808/189477964-8e0bfc9f-90de-43fc-92f8-950b4307620d.png)![T_Generic_Wall_Color_12_Base.png](https://user-images.githubusercontent.com/112512808/189477968-1c5a91b8-34f0-4a3b-b15a-f2fb4b30f362.png)![T_Generic_Wall_Color_11_Base.png](https://user-images.githubusercontent.com/112512808/189477973-cba76ff2-c933-4249-bb61-672470572c03.png)[]()![T_Generic_Wall_Color_10_Base.png](https://user-images.githubusercontent.com/112512808/189477975-cf36a035-c9b1-4640-bf70-15add45a86f2.png)![T_Generic_Wall_Color_1_Base.png](https://user-images.githubusercontent.com/112512808/189477977-92b30a2d-c757-4f5a-b1a4-a366d23a1067.png)

**Comment by BecBrock** [comment]
Thanks for updating! Approved.

**Comment by professaurChris** [comment]
Works.
