### ISSUE TITLE
2D Art Arcade and T-Shirt Art

### ISSUE THREAD

**Issue by BecBrock** [GAME-2332/project1#76]
Make 2D art for t-shirts in Spicy Subject and arcade machines. Save as a png using the examples below.

[] 3 t-shirts
[] 3 Arcade boxes
[] 3 Posters to match the arcade boxes
[] Air hockey table

Create texture names in file format
T_[StoreName][TeatureName][Description]_[#]_Base.png

Example:
T_Generic_Carpet_Blue_01_Base.png
T_Generic_Carpet_Red_01_Base.png
T_Arcade_Carpet_Galaxy_01_Base.png
T_Arcade_Carpet_DarkGreen_01_Base.png
T_Generic_Marble_White_01_Base.png
T_Generic_Marble_White_02_Base.png
T_Generic_Marble_White_03_Base.png

**Comment by michaelHkitchener** [comment]
![Image](https://user-images.githubusercontent.com/112128020/190240624-98e0b70a-ce85-4719-9659-ebe2eead2b02.png)



![Image](https://user-images.githubusercontent.com/112128020/190245571-7ff7f7f9-6ccd-4d53-acce-09c73208e964.png)



![Image](https://user-images.githubusercontent.com/112128020/190259897-69913076-67c5-47ef-95a8-f8309a93f069.png)

**Comment by michaelHkitchener** [comment]
shirts........

**Comment by michaelHkitchener** [comment]
![Image](https://user-images.githubusercontent.com/112128020/190263836-4a0b9fbc-db36-47a3-92c9-d5fd9681719b.png)
![Image](https://user-images.githubusercontent.com/112128020/190263837-210628fb-fc16-43c5-9b84-65c2a6d3cecf.png)
![Image](https://user-images.githubusercontent.com/112128020/190263838-9cbac291-39f9-4493-ae7d-5a660b964eff.png)

**Comment by michaelHkitchener** [comment]
transparency turned off for clear background png.

**Comment by BecBrock** [comment]
Shirts look good

**Comment by BecBrock** [comment]
We're scrapping the air hocky table, so don't worry about that.

**Comment by michaelHkitchener** [comment]
![Image](https://user-images.githubusercontent.com/112128020/191533264-62017b8d-67a9-47a7-bdda-0e8ea77be4c8.png)
![Image](https://user-images.githubusercontent.com/112128020/191533267-1fc0a028-e08d-4cae-8a67-3df3c98509df.png)
![Image](https://user-images.githubusercontent.com/112128020/191533266-2c1291ef-c098-4b58-9a55-608b049eeeed.png)
![Image](https://user-images.githubusercontent.com/112128020/191533265-b10ce6b3-ffe9-4d7e-9455-2e324b52402b.png)

**Comment by BecBrock** [comment]
approved

**Comment by professaurChris** [comment]
We're good on this.
