### ISSUE TITLE
Save state

### ISSUE THREAD

**Issue by aeonic-dev** [GAME-2332/project1#89]
Save states for persistent data between scenes and, if there's time, saved/loaded to/from disk. Mainly need to track object positions, forces, inventory, quest completion and other game state flags.

## SaveMe
- If you're a designer, this is the one you'll need to worry about
- Add it to any object to save and load specific data
- Can save transform values and rigidbody velocity by default
- Other components attached to the same object will be saved if they have the `IRuntimeSerialized` marker interface
- Takes care of assigning a persistent UID in the editor build, which is used at runtime
## SceneData
- Component attached to one object in each scene
- Defines which data needs to be serialized within the scene (manually added, or fetched dynamically by the inclusion of a `SaveMe` component)
- Maps game objects by unique identifiers obtained through `SaveMe#identifier`
- Stores a list of game objects that have been destroyed to destroy again if the scene is deserialized
## SaveState
- Object instance under GameManager, created at startup for the selected save slot
- Stores the actual current game's save state for a given slot
- Holds any non-scene-attached data between scenes (inventory, etc)
- When a scene is loaded, writes the last one to disk and sets up the now active SceneData for serialization; if data exists on the disk for this save slot it loads that to the SceneData object
- Stores a reference to only one active SceneData object at a time
- Contains a `LoadScene` method that must be used in place of `SceneManager#LoadScene`

**Comment by professaurChris** [comment]
Need a way to test this.

**Comment by aeonic-dev** [comment]
Closed after testing last thurs
